"""Documented analytical schema for BI and application consumers."""

from __future__ import annotations

LISTING_DICTIONARY = [
    ("listing_id", "string", "Stable source listing identifier"),
    ("name", "string", "Listing title"),
    ("listing_url", "string", "Source listing URL"),
    ("host_id", "string", "Stable source host identifier"),
    ("host_name", "string", "Host display name"),
    ("host_is_superhost", "boolean", "Source superhost flag"),
    ("host_identity_verified", "boolean", "Source identity-verification flag"),
    ("country", "string", "Country name from address"),
    ("country_code", "string", "Country code from address"),
    ("market", "string", "Airbnb market from address"),
    ("government_area", "string", "Administrative/neighborhood area from address"),
    ("suburb", "string", "Suburb from address"),
    ("longitude", "number", "GeoJSON longitude; first coordinate"),
    ("latitude", "number", "GeoJSON latitude; second coordinate"),
    ("coordinate_valid", "boolean", "Coordinate pair has numeric values in world bounds"),
    ("coordinate_issue", "string", "Reason a coordinate pair is invalid"),
    ("location_exact", "boolean", "Source location-exactness flag"),
    ("property_type", "string", "Source property type"),
    ("room_type", "string", "Source room type"),
    ("bed_type", "string", "Source bed type"),
    ("accommodates", "number", "Maximum guest count"),
    ("bedrooms", "number", "Bedroom count; missing remains null"),
    ("bathrooms", "number", "Bathroom count; missing remains null"),
    ("beds", "number", "Bed count; missing remains null"),
    ("minimum_nights", "number", "Minimum-night rule"),
    ("maximum_nights", "number", "Maximum-night rule"),
    ("price", "number", "Nightly source value; currency is not supplied"),
    ("price_unit", "string", "Always 'source price units'"),
    ("currency_verified", "boolean", "False because the source has no currency field"),
    ("cleaning_fee", "number", "Source cleaning fee; missing remains null"),
    ("security_deposit", "number", "Source security deposit; missing remains null"),
    ("extra_people", "number", "Source extra-person amount"),
    ("guests_included", "number", "Guests included in the source price"),
    ("price_missing", "boolean", "Price is absent or unparsable"),
    ("price_non_positive", "boolean", "Price is zero or negative"),
    ("price_extreme", "boolean", "Positive price outside its market 3-IQR outer fences"),
    ("price_outlier_lower", "number", "Market-specific lower outer fence"),
    ("price_outlier_upper", "number", "Market-specific upper outer fence"),
    ("review_score_rating", "number", "Overall review score on the source 0-100 scale"),
    ("number_of_reviews", "number", "Source review count"),
    ("availability_30", "number", "Snapshot of available days in next 30 days"),
    ("availability_60", "number", "Snapshot of available days in next 60 days"),
    ("availability_90", "number", "Snapshot of available days in next 90 days"),
    ("availability_365", "number", "Snapshot of available days in next 365 days"),
    ("availability_valid", "boolean", "All supplied horizon values are in valid bounds"),
    ("first_review", "date", "Source first-review timestamp"),
    ("last_review", "date", "Source last-review timestamp"),
    ("last_scraped", "date", "Source scrape timestamp"),
    ("calendar_last_scraped", "date", "Source calendar scrape timestamp"),
    ("amenities_count", "number", "Count of source amenities"),
    ("amenities", "string", "Pipe-delimited source amenities for BI filtering"),
    ("source_file", "string", "Input file name for provenance"),
    ("source_row", "number", "Zero-based position in the source array"),
]

REVIEW_DICTIONARY = [
    ("review_id", "string", "Stable source review identifier"),
    ("listing_id", "string", "Listing foreign key"),
    ("review_date", "date", "Parsed review date"),
    ("review_year_month", "string", "Calendar month for review-activity proxy charts"),
    ("market", "string", "Listing market, denormalized for BI filters"),
    ("government_area", "string", "Listing area, denormalized for BI filters"),
    ("country", "string", "Listing country, denormalized for BI filters"),
    ("source_listing_row", "number", "Zero-based listing position in source array"),
]

